ninja code
javascript-tutorial/hi.javascript.info pull request #37
Opened 2020-10-01 10:12 UTC by ayushhagarwal

Creating pull request for translation of ninja code section. Will review it once again myself and other other reviews and comments are welcomed.

2020-10-04 06:58 UTC, theBstar reviewed
Thanks for the MR @ayushhagarwal. I can see a lot of potential improvements. You can use the preview tab on the Github ci or just go through the translated article on your favourite IDE and make any required improvements. Let me know if you have already done the initial review. I can run through it post that.

2020-10-04 06:58 UTC, theBstar commented on 1-js/03-code-quality/04-ninja-code/article.md
> +```उद्धरण लेखक = "कन्फ्यूशियस (अनालेक्ट्स)"
These are smart tags, used by the page generator to generate the doc site. The site generator will fail if we change them.

2020-10-04 07:31 UTC, theBstar requested changes
Thanks for the PR @ayushhagarwal. I can see a lot of potential improvements. You can use the preview tab on the Github ci or just go through the translated article on your favourite IDE and make any required improvements. Let me know if you have already done the initial review. I can run through it post that.

2020-10-04 12:06 UTC, ayushhagarwal commented
I have made changes to t he quote and also made my  final review. You can go for your review and then suggest if any more improvements required.

2021-05-28 18:34 UTC, theBstar commented
Sorry, @ayushhagarwal I missed your comment completely. You will have to click on the request review once, so one of the reviewers gets notified. I will review this Sunday evening. Thanks anyway

2022-11-01 16:48 UTC, closed without merging